feature(REPORT-333396): Bold-Reports 5.3 Release Changes
boldreports/react-samples pull request #14
Opened 2023-10-30 11:08 UTC by RamyaManickam1927

<table>
<tr>
<td>
Description:
</td>
<td>
Bold-Reports 5.3 Release Changes
</td>
</tr>
<tr>
<td>
Analysis:
</td>
<td>
Analyzed about 5.3 release changes in javascript-reporting-controls package
</td>
</tr>
<tr>
<td>
Reason for not identifying earlier:
</td>
<td>
It's a new feature
</td>
</tr>
<tr>
<td>
Is it a breaking issue?
</td>
<td>
No, It's a new feature
</td>
</tr>
<tr>
<td>
Solution description:
</td>
<td>
Include the 5.3 release changes for package javascript-reporting-controls
</td>
</tr>
<tr>
<td>
Areas affected and ensured:
</td>
<td>
NA
</td>
</tr>
<tr>
<td>
Test cases:
</td>
<td>
NA
</td>
</tr>
<tr>
<td>
Test bed sample location:
</td>
<td>
VS, VS Code
</td>
</tr>
</table>

2023-10-30 15:50 UTC, karthickthangasamy requested changes

2023-10-30 15:50 UTC, karthickthangasamy commented on README.md
> +## Pre-requisite
revert this file changes

2023-10-31 05:23 UTC, RamyaManickam1927 commented on README.md
> +## Pre-requisite
Done

2023-11-06 05:54 UTC, karthickthangasamy approved these changes

2023-11-08 06:05 UTC, karthickthangasamy approved these changes

2023-11-08 06:05 UTC, merged